---

- name: Log into DockerHub
  docker_login:
    username: bachfischer
    password: 525cd1c2-5a40-4c17-ac5a-80266610f0ff
  become: yes
  environment: "{{ proxy_env }}"

# - name: Ensure GitHub deploy key is present on the server
#   copy:
#     content: "{{ ssh_deploy_key }}"
#     dest: ~/.ssh/cloud-assignment-git-repo-key
#     mode: '0600'

# # See: https://stackoverflow.com/a/37096534/100134
# - name: Ensure setfacl support is present.
#   package: name=acl
#   become: true
#   environment: "{{ proxy_env }}"

- name: Make sure that github code repo directory exists
  file:
    path: '~/cluster-and-cloud-computing-assignment-2'
    state: 'directory'

- name: Clone the code repository into home directory
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/Bachfischer/cluster-and-cloud-computing-assignment-2.git"
    dest: ~/cluster-and-cloud-computing-assignment-2
  environment: "{{ proxy_env }}"
  become: true

# Build image only on one host
- name: Build an image and push it to a private repo
  docker_image:
    build:
      path: '~/cluster-and-cloud-computing-assignment-2/twitter-harvester/'
      pull: yes
    name: bachfischer/cloud-assignment-2
    tag: latest
    push: yes
    source: build
  become: yes
  environment: "{{ proxy_env }}"