DATABASE_URL='http://172.26.132.56:5984/'
DATABASE_USERNAME='admin'
DATABASE_PASSWORD='data-miner!'
CREDENTIALS_DATABASE='twitter_credentials'
CITIES_DATABASE='cities'
SEARCH_TERM_DATABASE='search_terms'
SEARCH_TERM='climate_change'
REPOSITORY_DATABASE='new_twitter_examples'