version: '3'

services:

    backend:
        build: ./backend
        image: liamjsimon/backend
        expose:
            - 80
        environment:
            API_HOST: ${API_HOST}
            APP_SERVER_PORT: ${APP_SERVER_PORT} 
        ports:
            - ${APP_SERVER_PORT}:80
        volumes:
            - ./backend/src:/app/src
        command: npm run start

    frontend:
        build: ./frontend
        image: liamjsimon/frontend
        environment:
            REACT_APP_PORT: ${REACT_APP_PORT}
        expose:
            - 80
        ports:
            - ${REACT_APP_PORT}:80
        volumes:
            - ./frontend/src:/app/src
            - ./frontend/public:/app/public
        links:
            - backend
        command: nginx -g 'daemon off;'
