version: '3'

services:

    backend:
        build: ./backend
        image: liamjsimon/backend
        environment:
            API_HOST: ${API_HOST}
            APP_SERVER_PORT: ${APP_SERVER_PORT} 
        ports:
            - ${APP_SERVER_PORT}:${APP_SERVER_PORT} 
        command: npm run start

    frontend:
        build: ./frontend
        image: liamjsimon/frontend
        environment:
            REACT_APP_PORT: ${REACT_APP_PORT}
        ports:
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        stdin_open: true
        links:
            - backend
        command: serve -p 4000 -s .
        
